### ISSUE TITLE
Problem with Inertia Matrix

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/iit-frankapanda-ros-pkg#3]
# Problem with inertia matrix 

I was using the model of the franka in this repo with xbot. When I was retrieving the inertia matrix with xbot (command used:  _robot->model().getInertiaMatrix(_M);) such a matrix was all zero (disaster for the calculations).

Btw, after having asked to luca, he suggested in the model (i.e. in the urdf) such parameters might not be there. 

After hours of checking here in there, and trying to make the model we have in the repo as the one here : https://github.com/frankaemika/franka_description/tree/main/robots to find the problem.... 

Then I found that here 

https://github.com/ADVRHumanoids/iit-frankapanda-ros-pkg/blob/1e7a8d20063899c056571dc3a408d986a3be2a72/frankapanda_urdf/urdf/common/utils.xacro#L52C1-L54C18

in the file [iit-frankapanda-ros-pkg](https://github.com/ADVRHumanoids/iit-frankapanda-ros-pkg/tree/master)/[frankapanda_urdf](https://github.com/ADVRHumanoids/iit-frankapanda-ros-pkg/tree/master/frankapanda_urdf)/[urdf](https://github.com/ADVRHumanoids/iit-frankapanda-ros-pkg/tree/master/frankapanda_urdf/urdf)/[common](https://github.com/ADVRHumanoids/iit-frankapanda-ros-pkg/tree/master/frankapanda_urdf/urdf/common)/utils.xacro

the inertial parameter attached to the link is wrapped inside a IF GAZEBO which made me cry :'(

After having remove it, in the xbot plugin code blabla the inertial matrix appears! :D Now I can see not zero in the 7x7 

@torydebra gentle guy can you check it?

**Comment by torydebra** [comment]
yes, that tag was off because we do not want the gazebo plugin since we are using the xbot ones. But we need the inertial tag, so your fix is correct can you push with the if gazebo removed for the inertial tag?
